# .github/workflows/ci.yml

name: Build and Test

on:
  push:
    branches: [ "main", "Task/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test: # Changed job name to be more descriptive
    name: Build and Test on iOS Simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: swift build -v
        
      - name: Run tests
        run: swift test -v

      - name: Notify Telegram on Status
        # This step runs regardless of whether the build/test succeeded or failed.
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="✅ Build Succeeded"
          else
            STATUS="❌ Build Failed"
          fi
          
          # Create a URL-encoded message for the Telegram API
          MESSAGE="${STATUS}%0A%0A📦 *Repo:* ${{ github.repository }}%0A🌿 *Branch:* ${{ github.ref_name }}%0A%0A🔗 [View Build Log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

          # Send the message using curl
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            -d text="${MESSAGE}"
