# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "TASK/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

    - name: Notify Telegram
      if: always() # Important: This runs the step even if the build fails
      run: |
        STATUS="✅ Build succeeded"
        if [ "${{ job.status }}" != "success" ]; then
          STATUS="❌ Build failed"
        fi
        
        MESSAGE="${STATUS}%0A📦 Repo: $GITHUB_REPOSITORY%0A🌿 Branch: $GITHUB_REF_NAME%0A🔗 [View build]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"

        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="${MESSAGE}"
